---
title: Lukas Himsel
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
safe: false
markdown: kramdown
highlighter: rouge
lsi: false
permalink: "/:title"
description: Lukas Himsels persönliche Website mit Themen wie Musik, Klaviere, Open-Data,
  Open-Source und Webprojekten.
baseurl: ''
url: http://himsel.me
twitter_username: lukashimsel
github_username: lukas-h
accent: "#f7f7e6"
author: Lukas Himsel
address: Manegoldstraße 11<br>97346 Iphofen, DE
email: lukas@himsel.me
isolang: de
exclude:
- LICENSE
- README.md
replacements:
- - "<img"
  - "<amp-img"
- - alt="" />
  - ' layout="responsive" height="300px" width="600px"></amp-img>'
- - "<video"
  - "<amp-video"
- - "</video"
  - "</amp-video"
